### ISSUE TITLE
这个怎么用啊请问能提供下详细使用说明吗?

### ISSUE THREAD

**Issue by zhayo0** [xjasonlyu/jellyfin-plugin-avdc#1]
这个怎么用啊.请问能提供下详细使用说明吗?

**Comment by xjasonlyu** [comment]
我晚点更新下文档好了

**Comment by zhayo0** [comment]
安装插件没问题.就是AVDC的服务器架设没有详细安装说明.有点搞不懂.看了那边的文档,好像不是在群晖环境下做的.所以很多变量没法自己设置.还挺麻烦的.

**Comment by xjasonlyu** [comment]
我也用的是群辉，命令行可以配置，那我等下更新一下图文教程好了。

**Comment by zhayo0** [comment]
谢谢大佬,其实东西没啥看头,收藏还是很有乐趣的

**Comment by xjasonlyu** [comment]
Wiki已更新：https://github.com/xjasonlyu/avdc-api/wiki/Synology-%E7%BE%A4%E6%99%96%E5%AE%89%E8%A3%85%EF%BC%88%E5%8D%81%E5%88%86%E6%8E%A8%E8%8D%90%EF%BC%89

**Comment by zhayo0** [comment]
感谢.已经安装好了.jellyfin里演员表头像还是不显示.但是点进去之后会显示大头像.重新点开,才能看到头像

**Comment by xjasonlyu** [comment]
Jellyfin拉取元数据和头像不是同步的，所以需要等几秒让它自己刷新或者手动刷新浏览器。

**Comment by zhayo0** [comment]
那如果我想让头像显示.需要怎么操作呢

**Comment by xjasonlyu** [comment]
什么叫让头像显示？难道它没有显示出来吗？截图看看？

**Comment by zhayo0** [comment]
演员表这里不显示头像
![QQ截图20210323162256](https://user-images.githubusercontent.com/49388625/112115484-33aa1e00-8bf4-11eb-951f-fac915429eff.png)
但是这个不显示头像的演员表点进去.会有头像大图
![QQ截图20210323162358](https://user-images.githubusercontent.com/49388625/112115618-5ccaae80-8bf4-11eb-923d-e3cfaa4ddfe4.png)

**Comment by xjasonlyu** [comment]
浏览器上面那个刷新按钮，点一下，是浏览器缓存的问题。

**Comment by zhayo0** [comment]
刷新刷不出来的.只能点进大图过后.会出现

**Comment by xjasonlyu** [comment]
你能看到头像了就说明头像已经下载到jellyfin库里了，至于不能在演员表里看到应该是你jellyfin或者浏览器的问题吧，我本地不能复现出这个问题
