### ISSUE TITLE
大佬能否给插件提供优先选择源站的选项

### ISSUE THREAD

**Issue by LNai** [xjasonlyu/jellyfin-plugin-avdc#11]
不知是不是插件抽风还是源网站限制 添加文件时可以自动识别到其中的一个影片 其他的需要手动识别才可以 识别几个后又不可以了 确定网络没问题 软路由挂clash 局域网可翻 为证明NSA也可以翻特意下载docker版chrome访问youtube javbus均可。
所有有点怀疑是不是某些源网站出现问题，希望作者能够给插件支持的源网站选择排序 优先选择排在最前面的网站刮削 看看能不能排除问题
#9 问题基本和这个类似
插件版本 2021.406.740.0
jellyfin版本 10.7.1
插件日志
[avdc-api .zip](https://github.com/xjasonlyu/jellyfin-plugin-avdc/files/6279232/avdc-api.zip)

**Comment by xjasonlyu** [comment]
你的日誌裡是數據庫造成的，重新拉一下鏡像就可以了，和源站幾乎沒有關係的樣子。

**Comment by LNai** [comment]
> 你的日誌裡是數據庫造成的，重新拉一下鏡像就可以了，和源站幾乎沒有關係的樣子。

大佬 重新拉取下镜像确实可以了 但是目前只能看到图片 却看不到影片信息及演员 去影片目录里看NFO文件却是存在的 还是需要手动识别才行

**Comment by xjasonlyu** [comment]
不可能吧🤔插件日誌和api日誌沒報錯的話就應該沒問題了

**Comment by LNai** [comment]
大佬这是最新的日志 您帮忙看下 难道还是数据库错误🤔
[avdc-api.zip](https://github.com/xjasonlyu/jellyfin-plugin-avdc/files/6279824/avdc-api.zip)

**Comment by xjasonlyu** [comment]
你網絡超時比較多，是不是你節點不太行👀

**Comment by LNai** [comment]
> 你網絡超時比較多，是不是你節點不太行👀

这就难受了 但是刚刚去影视目录看了下nfo文件 虽然刮下来了 但是里面的文本却不是很齐全 所以导致无法显示影片介绍和演员表 这个难道网络超时只爬一半？有点不可思议
[无问题nfo.zip](https://github.com/xjasonlyu/jellyfin-plugin-avdc/files/6279976/nfo.zip)
[有问题nfo.zip](https://github.com/xjasonlyu/jellyfin-plugin-avdc/files/6279977/nfo.zip)

**Comment by xjasonlyu** [comment]
如果你要重新刮的話，可以考慮先把數據庫清空，可能之前有一些不完整的數據在裡面

**Comment by LNai** [comment]
您指的数据库是影片目录里之前刮下来的图片和nfo文件吗 这些我刚刚试了全部删除只保留影片 然后在jellyfin中再删除媒体库然后再添加 但是还是和之前的一样图片和nfo文件都刮下来了 但是nfo里面的文本就是不全导致影片介绍界面没有介绍和演员表

![1](https://user-images.githubusercontent.com/18456071/114065509-506d7380-98cd-11eb-9d7e-9d2d3f525914.jpg)
难受 弄了一天 谢谢大佬这么晚还在解答 先打个盹去。。。。

**Comment by xjasonlyu** [comment]
是那个avdc.db文件，你不会清数据的话就删了重新下一个再重启就行了

**Comment by LNai** [comment]
> 是那个avdc.db文件，你不会清数据的话就删了重新下一个再重启就行了

删掉avdc.db 重新下载上传重启后依旧还是老问题  算了我还是一个个手动识别吧 反正也不多 影片看不看已经为所谓了 主要是喜欢折腾 哈哈

**Comment by LNai** [comment]
经过一上午折腾 重新拉取镜像进行安装 然后我把容器自带的内部端口设置为5001 因为我的NAS开启了https访问（不知道和这个有没有影响） 最终经过测试后插件工作正常
