### ISSUE TITLE
请求里番支持

### ISSUE THREAD

**Issue by NiuXZi** [xjasonlyu/jellyfin-plugin-avdc#12]
如题，里番也是很不错的

**Comment by xjasonlyu** [comment]
里番，是dlsite里的那种嘛。。。

**Comment by NiuXZi** [comment]
> 里番，是dlsite里的那种嘛。。。

那里面大多是漫画游戏吧。
里番，是黄色动画啊

**Comment by xjasonlyu** [comment]
我都不知道哪里有=_=

**Comment by NiuXZi** [comment]
琉璃神社
https://www.liuli.cat/wp/
和一个外国网站
https://members.hanime.tv/
我就知道这俩活得比较久了

**Comment by xjasonlyu** [comment]
沒番號的嘛

**Comment by NiuXZi** [comment]
> 沒番號的嘛

里番貌似是没有的。。。大意了
