### ISSUE TITLE
老哥问下怎么我的女优图片不显示

### ISSUE THREAD

**Issue by kkh66** [xjasonlyu/jellyfin-plugin-avdc#13]

**Comment by kkh66** [comment]
[avdc.txt](https://github.com/xjasonlyu/jellyfin-plugin-avdc/files/6290480/avdc.txt)

**Comment by xjasonlyu** [comment]
日誌沒有問題

**Comment by kkh66** [comment]
我找是没有问题可是女优没有头像

**Comment by xjasonlyu** [comment]
你手動識別可以顯示嘛

**Comment by kkh66** [comment]
我手动识别有识别女优可是还是没头像也找不到相关作品

**Comment by xjasonlyu** [comment]
你必須要提供更詳細的信息比如插件日誌版本、後端版本等，不然我也不知道怎麼回事。

**Comment by LNai** [comment]
#9 可以参考下这个

**Comment by kkh66** [comment]
> #9 可以参考下这个

感谢老哥你的方法解决了我的问题
