### ISSUE TITLE
可否增加简介中文翻译的选项呢？

### ISSUE THREAD

**Issue by kamen-exaid** [xjasonlyu/jellyfin-plugin-avdc#14]
从隔壁过来的，配置了一会儿终于搞定啦。感谢大佬！！

不知道可否增加 标题、简介 的中文翻译的选项呢？
还有就是在配置过程中一直无法确定插件是否已经通过代理连接上了网络，感觉可以增加一个测试按钮之类的哈哈哈。。

**Comment by xjasonlyu** [comment]
1. 个人认为翻译没什么用，机翻不如不翻
2. 代理测试直接进shell测试就可以了

**Comment by kamen-exaid** [comment]
翻译看一下大概的剧情其实也还行啦。。

PS:昨天使用以后发现隔壁不能刮的部分番号这个也可以刮了！只是有部分封面的裁剪会有一丢丢小问题，截图位置对的不是脸，是一些奇奇怪怪的位置

**Comment by xjasonlyu** [comment]
> PS:昨天使用以后发现隔壁不能刮的部分番号这个也可以刮了！只是有部分封面的裁剪会有一丢丢小问题，截图位置对的不是脸，是一些奇奇怪怪的位置

比如脸在封面左侧1/3位置，在手动识别那里输入番号加上位置，比如：`ABP-233?pos=0.33`，就可以修正裁剪了（只要番号后加上`?pos=0.xx`即可，注意0<=pos<=1）

**Comment by kamen-exaid** [comment]
解决了，感谢
