### ISSUE TITLE
插件突然不能用了

### ISSUE THREAD

**Issue by NiuXZi** [xjasonlyu/jellyfin-plugin-avdc#16]
RT，今天打开突然显示malfunctioned。
jellyfin版本 10.7.1
插件版本 2021.413.310

**Comment by xjasonlyu** [comment]
是avdc-api后端嘛？

**Comment by NiuXZi** [comment]
> 是avdc-api后端嘛？

docker后端，刚刚看了，{"message":"AVDC-API","status":true}

**Comment by kkh66** [comment]
> 是avdc-api后端嘛？

我也是这问题

**Comment by xjasonlyu** [comment]
可能是数据库损坏了，重新下载avdc.db就可以了

**Comment by xjasonlyu** [comment]
sqlite數據庫似乎經常有此類問題。

**Comment by kkh66** [comment]
> 可能是数据库损坏了，重新下载avdc.db就可以了

如果用之前的版本就没这问题

**Comment by kkh66** [comment]
显示这个此插件没有配置选项。

**Comment by kkh66** [comment]
> sqlite數據庫似乎經常有此類問題。

{
  "category": "Metadata",
  "changelog": "Auto Released by Actions",
  "description": "Provides additional metadata for adult videos by AVDC.",
  "guid": "001c811c-145d-4b43-94bf-f78e8d7b6afd",
  "name": "AVDC",
  "overview": "AVDC Metadata Provider for Jellyfin",
  "owner": "xjasonlyu",
  "targetAbi": "10.7.0.0",
  "timestamp": "2021-04-13T03:10:35.0000000Z",
  "version": "2021.413.310",
  "status": "Malfunctioned",
  "autoUpdate": true,
  "imagePath": ""
}
这个是metajson的数据

**Comment by xjasonlyu** [comment]
？原來是說下載插件嗎，我等下去看看==

**Comment by kkh66** [comment]
> ？原來是說下載插件嗎，我等下去看看==

是的我的后端没问题

**Comment by xjasonlyu** [comment]
> RT，今天打开突然显示malfunctioned。
> jellyfin版本 10.7.1
> 插件版本 2021.413.310

试一下更新Jellyfin到10.7.2。

**Comment by kkh66** [comment]
> > RT，今天打开突然显示malfunctioned。
> > jellyfin版本 10.7.1
> > 插件版本 2021.413.310
> 
> 试一下更新Jellyfin到10.7.2。

感谢终于好了

**Comment by NiuXZi** [comment]
> > RT，今天打开突然显示malfunctioned。
> > jellyfin版本 10.7.1
> > 插件版本 2021.413.310
> 
> 试一下更新Jellyfin到10.7.2。

好的，已解决
