### ISSUE TITLE
jellyfin10.8.0,插件显示Malfunctioned

### ISSUE THREAD

**Issue by liwenjie119** [xjasonlyu/jellyfin-plugin-avdc#17]
在插件页面，插件状态显示Malfunctioned，是还不支持这个版本吗？

**Comment by xjasonlyu** [comment]
你告诉我Jellyfin哪来的10.8.0 ==

**Comment by liwenjie119** [comment]
突然发现用的linuxserver/jellyfin:nightly

**Comment by liwenjie119** [comment]
换成linuxserver/jellyfin:latest就好了

**Comment by xjasonlyu** [comment]
插件不支持beta，nightly的

**Comment by Zirong007** [comment]
您好 作者 我也是这个问题 
![Screenshot_20210416-011711](https://user-images.githubusercontent.com/69599873/114912145-3f36e080-9e52-11eb-8aea-9248f5678263.jpg)
![Screenshot_20210416-011649](https://user-images.githubusercontent.com/69599873/114912164-44942b00-9e52-11eb-9fdb-653b26fc1a73.jpg)

**Comment by kkh66** [comment]
> 您好 作者 我也是这个问题
> ![Screenshot_20210416-011711](https://user-images.githubusercontent.com/69599873/114912145-3f36e080-9e52-11eb-8aea-9248f5678263.jpg)
> ![Screenshot_20210416-011649](https://user-images.githubusercontent.com/69599873/114912164-44942b00-9e52-11eb-9fdb-653b26fc1a73.jpg)

升级去10.7.2

**Comment by Zirong007** [comment]
> > 您好 作者 我也是这个问题
> > ![Screenshot_20210416-011711](https://user-images.githubusercontent.com/69599873/114912145-3f36e080-9e52-11eb-8aea-9248f5678263.jpg)
> > ![Screenshot_20210416-011649](https://user-images.githubusercontent.com/69599873/114912164-44942b00-9e52-11eb-9fdb-653b26fc1a73.jpg)
> 
> 升级去10.7.2

升级完解决了 哈哈哈 好爽
