### ISSUE TITLE
插件安装重启后状态是Malfunctioned，并且点击后提示没有配置选项

### ISSUE THREAD

**Issue by zht826** [xjasonlyu/jellyfin-plugin-avdc#20]
![image](https://user-images.githubusercontent.com/21307445/115580227-7b0df200-a2f9-11eb-80f2-547fc43882b5.png)
![image](https://user-images.githubusercontent.com/21307445/115580256-8103d300-a2f9-11eb-849e-efe4f614bf9c.png)
插件安装重启后状态是Malfunctioned，并且点击后提示没有配置选项

**Comment by xjasonlyu** [comment]
jellyfin>=10.7.2

**Comment by zht826** [comment]
我以为10.7.0就可以，我升级试试
