### ISSUE TITLE
老哥问个问题

### ISSUE THREAD

**Issue by kkh66** [xjasonlyu/jellyfin-plugin-avdc#21]
问下库里的id怎么用像javbus的id怎样用我发现一些明明javbus有可是还是搜寻错误

**Comment by kkh66** [comment]
我在tma遇到最大这种问题比如26ID-051 然后插件搜寻ID-051 找到的是其他的不是我要的那个怎样用id帮填对

**Comment by xjasonlyu** [comment]
你问的什么到底是，明明中文是在用。例子具体给一个？

**Comment by Zirong007** [comment]
> 你问的什么到底是，明明中文是在用。例子具体给一个？

有开发emby的插件吗 感觉您的插件比javscrap好用

**Comment by xjasonlyu** [comment]
Release里不是有Emby的插件吗。。

**Comment by kkh66** [comment]
> 你问的什么到底是，明明中文是在用。例子具体给一个？

如果搜寻26ID-051他会搜到ID-051 ミニスカニーソックス BEST 4時間 这个，可是明明是ID-051 童貞を殺す服を着た美少女 PREMIUM BEST 8時間 想问下能不能靠给javdb的id来认证

**Comment by xjasonlyu** [comment]
你直接识别里用`ID-051`搜索就行了啊

**Comment by kkh66** [comment]
> 你直接识别里用`ID-051`搜索就行了啊

tma系列的容易遇到类似的问题尤其是id系列，不管怎么改容易搜到错误的

**Comment by xjasonlyu** [comment]
这是jav321的源问题吧，他就是那么显示的

**Comment by kkh66** [comment]
老哥问下识别的那些数据元里面的id是怎样用的

**Comment by xjasonlyu** [comment]
目前就`AVDC`那个ID可以用，其他只是作为外部链接用

**Comment by kkh66** [comment]
哦哦，想问下老哥你以后会不会支持那些数据元，之前我以为可以用的试下把网址放在哪里可是一直搜寻不成功

**Comment by xjasonlyu** [comment]
没什么必要吧，有番号直接搜索就可以了，理论上没有问题

**Comment by kkh66** [comment]
> 没什么必要吧，有番号直接搜索就可以了，理论上没有问题

好吧感谢回答，主要是tma的真的容易出问题有的时候真的要用特定的方式才能搜到

**Comment by xjasonlyu** [comment]
为啥jav321就是这样的，你可以直接命名为ID-XXX这样

**Comment by xjasonlyu** [comment]
更新插件以及avdc-api後端之後，可以在手動識別的名字處使用如：`abp-123?providers=javbus`來指定提供源

**Comment by kkh66** [comment]
> 更新插件以及avdc-api後端之後，可以在手動識別的名字處使用如：`abp-123?providers=javbus`來指定提供源

感谢老哥
