### ISSUE TITLE
ARM架构的都不支持嘛

### ISSUE THREAD

**Issue by huangbinyu1987** [xjasonlyu/jellyfin-plugin-avdc#22]
ARM架构不支持吗？
1、ARM架构无法搭建ACDB-API
2、用Hyper虚拟机搭建ACDB，X86 Docker安装emby/jellyfin可以使用
3、用Hyper虚拟机搭建ACDB，PC安装emby/jellyfin 可以使用
4、用Hyper虚拟机搭建ACDB，ARM（N1） openwrt docker安装emby/jellyfin无法使用，同条件下PC、X86 openwrt可以使用

想用 N1搭建，一直搞不定。是不是中间只要有ARM架构的设备就不能削刮？

**Comment by xjasonlyu** [comment]
暫時不支持x86以外的架構，因為人臉識別庫的需要。

**Comment by huangbinyu1987** [comment]
@xjasonlyu 好的，感谢。
