### ISSUE TITLE
影片后缀-cd1 cdX 识别异常

### ISSUE THREAD

**Issue by Zirong007** [xjasonlyu/jellyfin-plugin-avdc#23]
分集视频不知道为什么 显示在emby里面还是出现多个相同海报视频位

**Comment by xjasonlyu** [comment]
我没有这个问题，相关目录结构截个图之类的？

**Comment by Zirong007** [comment]
> 我没有这个问题，相关目录结构截个图之类的？

<img width="406" alt="截屏2021-05-05 下午5 52 22" src="https://user-images.githubusercontent.com/69599873/117124357-d09ed000-adca-11eb-97f3-2f1177d6de69.png">
<img width="627" alt="截屏2021-05-05 下午5 52 33" src="https://user-images.githubusercontent.com/69599873/117124362-d2689380-adca-11eb-8b61-d267d2b78ee0.png">
<img width="646" alt="截屏2021-05-05 下午5 52 46" src="https://user-images.githubusercontent.com/69599873/117124372-d4caed80-adca-11eb-8e42-9e9cf541ec34.png">

**Comment by xjasonlyu** [comment]
目測是Jellyfin的bug⋯⋯

**Comment by xjasonlyu** [comment]
我Emby很正常。

**Comment by Zirong007** [comment]
> 我Emby很正常。

我用的就是emby...... 最新的官方版本

**Comment by xjasonlyu** [comment]
那可以去emby提bug了，插件是不管cd分集的(>_>)

**Comment by xjasonlyu** [comment]
我好像知道你的问题了，cd分集需要一个共同目录，你这里就是需要上下两集放在`VRVR-078`目录下才可以。你现在是所有影片都放在一个大目录下所以才这样了。

**Comment by Zirong007** [comment]
> 我好像知道你的问题了，cd分集需要一个共同目录，你这里就是需要上下两集放在`VRVR-078`目录下才可以。你现在是所有影片都放在一个大目录下所以才这样了。

非常感谢 我这就去弄
