### ISSUE TITLE
Organize Genres已失败

### ISSUE THREAD

**Issue by dayunnas** [xjasonlyu/jellyfin-plugin-avdc#24]
Method not found: 'System.Collections.Generic.Dictionary`2<system.string,system.string> MediaBrowser.Controller.Entities.BaseItem.get_ProviderIds()'.
at Jellyfin.Plugin.AVDC.ScheduledTasks.OrganizeGenresTask.&lt;&gt;c.<execute>b__12_0(BaseItem item)
at System.Linq.Enumerable.WhereArrayIterator`1.ToList()
at Jellyfin.Plugin.AVDC.ScheduledTasks.OrganizeGenresTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)</execute></system.string,system.string>

**Comment by dayunnas** [comment]
emby最新4.6.0.43，每天凌晨2:00会自动运行一次，都是已失败

**Comment by dayunnas** [comment]
![image](https://user-images.githubusercontent.com/80449837/117103014-1bf5b600-adac-11eb-80c7-972264435182.png)

**Comment by xjasonlyu** [comment]
因为你用的是beta版。

**Comment by dayunnas** [comment]
> 因为你用的是beta版。

大佬，这个错误是什么意思？能帮忙大概说明下么？

**Comment by xjasonlyu** [comment]
可能是4.6.0的API变了

**Comment by xjasonlyu** [comment]
建议用回稳定版，或者禁用这个Task

**Comment by dayunnas** [comment]
> 建议用回稳定版，或者禁用这个Task

目前好像没啥影响，都能正常刮削，这个错误是啥意思？

**Comment by xjasonlyu** [comment]
没什么影响，就是会对每部影片的类型做个整理而已

**Comment by dayunnas** [comment]
> 没什么影响，就是会对每部影片的类型做个整理而已

哦哦，不影响刮削就算了，我用的群晖升上去就退不回来了，群晖套件里只有beta，希望大佬下个版本能修复这个bug，大佬幸苦了

**Comment by xjasonlyu** [comment]
你能不能把日志完整一点的截图，或者直接把日志发给我。。

**Comment by dayunnas** [comment]
> 你能不能把日志完整一点的截图，或者直接把日志发给我。。

怎么发？大佬加个VX？

**Comment by dayunnas** [comment]
[Uploading embyserver-63755820304.txt…]()

**Comment by dayunnas** [comment]
> 你能不能把日志完整一点的截图，或者直接把日志发给我。。

我发了，你看下是上面这个吗？

**Comment by xjasonlyu** [comment]
不是⋯

**Comment by xjasonlyu** [comment]
你没上传对

**Comment by dayunnas** [comment]
[embyserver-63755820304.txt](https://github.com/xjasonlyu/jellyfin-plugin-avdc/files/6425729/embyserver-63755820304.txt)

**Comment by dayunnas** [comment]
这次可以了吗？

**Comment by xjasonlyu** [comment]
可以了，我看看。

**Comment by dayunnas** [comment]
> 可以了，我看看。

感谢大佬，大佬有电报群吗？能拉我进去吗

**Comment by xjasonlyu** [comment]
没有，为啥这要有电报群😂

**Comment by dayunnas** [comment]
一群志同道合的人交流交流呀

**Comment by dayunnas** [comment]
以前一直用的Jav Scraper，升级beta后就失效了，无意中发现大佬的插件，真好用，就是这个错误每天一次，有点闹心，哈哈大佬牛逼

**Comment by dayunnas** [comment]
> 没有，为啥这要有电报群😂

还有个问题，你每次更新后，emby里的插件会自动更新吗？还是要重新下载后放入emby插件文件夹？还有后端部署的docker需要更新吗？？

**Comment by xjasonlyu** [comment]
> 还有个问题，你每次更新后，emby里的插件会自动更新吗？还是要重新下载后放入emby插件文件夹？还有后端部署的docker需要更新吗？？

计划任务每天会自动检查更新，下次重启emby就会重新载入插件

**Comment by dayunnas** [comment]
也就是说你这边更新了，我重启下emby就行了，其他都不用管（包括docker），666，太方便了

**Comment by xjasonlyu** [comment]
计划任务是每天凌晨执行的，或者你可以手动运行，然后重启emby也可以。

docker更新（如果需要的话）直接拉镜像就可以了。

**Comment by dayunnas** [comment]
这个都会，其他看你的更新说明（大佬的说明都是保姆级的），avdc.db这文件不需要更新吧

**Comment by xjasonlyu** [comment]
一般不需要，这个是用來存你每次刮出来的数据，除非出问题了再重新下一个

**Comment by dayunnas** [comment]
谢谢大佬答疑解惑，Organize Genres已失败原因找到了吗？下个版本可以修复吗？或者等正式版出来修复（听说4.6.0正式版快出来了）

**Comment by xjasonlyu** [comment]
你可以先禁用这个Task，这个Task基本就是类型去重之类的

**Comment by dayunnas** [comment]
大佬，你是不是修复了？哈哈，从昨天开始就没有报错了

**Comment by xjasonlyu** [comment]
修復了

**Comment by dayunnas** [comment]
大佬666，我要和你做朋友
