### ISSUE TITLE
关于手动识别问题

### ISSUE THREAD

**Issue by kkh66** [xjasonlyu/jellyfin-plugin-avdc#26]
不知道为什么手动识别会出现code 400
报错如下
119.82.29.13 - - [17/May/2021 18:14:38] code 400, message Bad request version ('\x1a\x1a\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93ÚÚ\x00\x00\x00\x17\x00\x00ÿ\x01\x00\x01\x00\x00')

119.82.29.13 - - [17/May/2021 18:14:38] "üßF8'¥1ñÔU[F(Í@$Àj»·9Øß¡6 ·;dfÔÓíóÉIQ4_[¹Ò+
ÍÍ<Ú× À+À/À,À0Ì©Ì¨ÀÀ/5ÚÚÿ" HTTPStatus.BAD_REQUEST -

119.82.29.13 - - [17/May/2021 18:14:39] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03\x04¦\x10')

119.82.29.13 - - [17/May/2021 18:14:39] "ü¦" HTTPStatus.BAD_REQUEST -

119.82.29.13 - - [17/May/2021 18:14:42] code 400, message Bad request version ('zz\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93êê\x00\x00\x00\x17\x00\x00ÿ\x01\x00\x01\x00\x00')

119.82.29.13 - - [17/May/2021 18:14:42] "ü'ÉÔßÑ0*Ï¾ËÌ6Ù	Ó(«Î
0z éì\ ºánðL
ýÙ9X££æ;2? zzÀ+À/À,À0Ì©Ì¨ÀÀ/5êêÿ" HTTPStatus.BAD_REQUEST -

119.82.29.13 - - [17/May/2021 18:14:42] code 400, message Bad request version ('\x11[(Á1»Õ\x06ÔÀs\x84m\x7fôø=;DÛTØP¾ÓÈ\xadp\x00"\x9a\x9a\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')

119.82.29.13 - - [17/May/2021 18:14:42] "ü÷i\î$F*Í®K)nnÜÀØ8N¾Å§)ÈÀ7Ç$ kÃ9[(Á1»ÕÔÀsmôø=;DÛTØP¾ÓÈ­p"À+À/À,À0Ì©Ì¨ÀÀ/5" HTTPStatus.BAD_REQUEST -

185.202.2.132 - - [17/May/2021 18:15:35] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')

185.202.2.132 - - [17/May/2021 18:15:35] "/*àCookie: mstshash=Administr" HTTPStatus.BAD_REQUEST -

之前没出现这种问题的

**Comment by kkh66** [comment]
图片没有显示不过还是可以照常识别只是找的时候看不到照片

**Comment by xjasonlyu** [comment]
你解释一下为什么有`HTTP/0.9`。。

**Comment by kkh66** [comment]
> 你解释一下为什么有`HTTP/0.9`。。

这我是真的不知道,只是我在portainer的log看后端时每次手动识别都会出现这个错误.我以为是我的服务器问题我特地用新的vps开后端可是还是会出现

**Comment by kkh66** [comment]
[_AVDC_logs.txt](https://github.com/xjasonlyu/jellyfin-plugin-avdc/files/6498440/_AVDC_logs.txt)

**Comment by xjasonlyu** [comment]
这是你客户端的问题，非常奇葩，而且我不知道是什么。。

**Comment by kkh66** [comment]
> 这是你客户端的问题，非常奇葩，而且我不知道是什么。。

好的，感谢解答
