### ISSUE TITLE
EMBY里面链接跳转打不开，显示about:blank#blocked

### ISSUE THREAD

**Issue by ati121** [xjasonlyu/jellyfin-plugin-avdc#27]

**Comment by xjasonlyu** [comment]
你瀏覽器的問題吧

**Comment by maplejaw** [comment]
我也遇到了，点xlist标签无法跳转， chrome浏览器

**Comment by xjasonlyu** [comment]
好的，我确认一下

**Comment by xjasonlyu** [comment]
已修复，晚一点会发布更新，重新刷新一下元数据即可。

**Comment by ati121** [comment]
已更新，v2021.0523.1000还是有问题。刷新了元数据测试跳转后https://xslist.org/zh/model/https:.html    类似这样

**Comment by xjasonlyu** [comment]
对，emby如果在已经有externalId的情况下，更新元数据是不会更新相关ID的，需要重新扫描媒体库（尝试重命名一下媒体库会触发重新扫描）

**Comment by ati121** [comment]
我新建了个媒体库，丢了2部进去试，影片链接正常了，演员链接还是如上

**Comment by xjasonlyu** [comment]
因为演员数据是独立于媒体库的，需要专门重置演员数据
