### ISSUE TITLE
大佬，今天突然刮削不了了

### ISSUE THREAD

**Issue by dayunnas** [xjasonlyu/jellyfin-plugin-avdc#29]
大佬，今天突然刮削不了了，版本emby4.6.1正式版
![image](https://user-images.githubusercontent.com/80449837/120164071-bf5fac80-c22c-11eb-8a76-175981abd9eb.png)

**Comment by dayunnas** [comment]
而且其他所有刮好的项目全部变了
![image](https://user-images.githubusercontent.com/80449837/120164292-00f05780-c22d-11eb-8b36-144df826d0cc.png)

**Comment by xjasonlyu** [comment]
这应该是你的问题，你可以自查一下或者提供具体的信息。

**Comment by xjasonlyu** [comment]
javbus更新了图床地址，更新一下avdc-api后端即可。

**Comment by dayunnas** [comment]
更新一下avdc-api后端是不是重新拉取下docker？AVDC.DB这个文件需要重新下载覆盖吗？

**Comment by xjasonlyu** [comment]
先拉镜像，成功的话就不需要覆盖，不行的话再覆盖。。

**Comment by dayunnas** [comment]
![image](https://user-images.githubusercontent.com/80449837/120251086-f8426480-c2b2-11eb-9916-a666d1a0b786.png)
还是刮削不了，要哭了~~

**Comment by dayunnas** [comment]
可以了，感谢群里的一位兄弟指导，感谢群主无私奉献
