### ISSUE TITLE
新版本插件好像没有设置服务器的配置了

### ISSUE THREAD

**Issue by zhayo0** [xjasonlyu/jellyfin-plugin-avdc#3]
新版本插件好像没有设置服务器的配置了

**Comment by zhayo0** [comment]
![QQ截图20210323213210](https://user-images.githubusercontent.com/49388625/112154449-40903700-8c1f-11eb-8e1f-b17dab9313e9.png)

**Comment by xjasonlyu** [comment]
你卸了重装试试，jellyfin小bug比较多。

**Comment by xjasonlyu** [comment]
或者看看日志里有没有报错

**Comment by zhayo0** [comment]
941 安装没问题.新版不行

**Comment by xjasonlyu** [comment]
jellyfin版本号？

**Comment by xjasonlyu** [comment]
jellyfin升到10.7.1了嘛，修了好多bug了。

**Comment by zhayo0** [comment]
10.7.0

**Comment by xjasonlyu** [comment]
建议更新到10.7.1

**Comment by zhayo0** [comment]
头像问题我用Gfriends Inputer 解决了.应该还是插件问题

**Comment by zhayo0** [comment]
就是稍微麻烦点.需要每次手动

**Comment by xjasonlyu** [comment]
本项目用的就是gfriends的图像，不明白你为啥载不出来⋯

**Comment by zhayo0** [comment]
但是用Gfriends Inputer手动.就能加载出来

**Comment by xjasonlyu** [comment]
问了几个其他使用者，貌似只有你有这个问题🌚

**Comment by zhayo0** [comment]
方便留个邮箱?我把账号密码发你.你帮我瞅瞅?

**Comment by xjasonlyu** [comment]
之後會有插件更新，打算再加個計劃任務作補充。

**Comment by xjasonlyu** [comment]
插件可更新
