### ISSUE TITLE
Malfunctioned故障

### ISSUE THREAD

**Issue by wenkangkevin** [xjasonlyu/jellyfin-plugin-avdc#30]
插件安装重启后，显示Malfunctioned
![image](https://user-images.githubusercontent.com/35211794/120212416-8cd1a600-c264-11eb-94c5-7dd0e56cb739.png)

**Comment by xjasonlyu** [comment]
jellyfin更新一下。

**Comment by wenkangkevin** [comment]
可以了，谢谢
