### ISSUE TITLE
正常的电影媒体库中没有勾选avdc，但avdc-api中还是有查询日志，并且导致正常的电影也无法搜索封面

### ISSUE THREAD

**Issue by huxim** [xjasonlyu/jellyfin-plugin-avdc#31]
![image](https://user-images.githubusercontent.com/2505801/120878091-bbe17200-c5ec-11eb-8eee-4d53b39dc374.png)
![image](https://user-images.githubusercontent.com/2505801/120878133-09f67580-c5ed-11eb-9f49-427a1b8c2715.png)

**Comment by xjasonlyu** [comment]
可能是jellyfin的bug吧

**Comment by huxim** [comment]
看起来是
