### ISSUE TITLE
请大佬更新支持jellyfin10.8版本啊。。。

### ISSUE THREAD

**Issue by fallenyy** [xjasonlyu/jellyfin-plugin-avdc#49]
jellyfin10.8对插件部分进行了更改，导致AVDC用不了，麻烦什么时候能支持下。

**Comment by xjasonlyu** [comment]
jellyfin 10.8还在beta2，他的官方sdk包还在10.7.7，为什么要这么早更新到10.8呢

**Comment by fallenyy** [comment]
> 



> jellyfin 10.8还在beta2，他的官方sdk包还在10.7.7，为什么要这么早更新到10.8呢

啊，是的，感觉上10.8比10.7好用太多，所以就升级了。因为正式版发布可能还需要很久，所以来找大佬了。。。

**Comment by xjasonlyu** [comment]
beta的接口变动大，支持起来费时没有意义的

**Comment by fallenyy** [comment]
> beta的接口变动大，支持起来费时没有意义的

额 ，好吧，那只能等正式版没改动了再来求了。谢谢
