### ISSUE TITLE
部署了刮削不到

### ISSUE THREAD

**Issue by gm-fire** [xjasonlyu/jellyfin-plugin-avdc#5]
![6290C5A1-3FFC-46EE-9123-7B24485D19C0](https://user-images.githubusercontent.com/5047482/112440767-a4cd0b00-8d85-11eb-98bf-ed42bb23a4a5.png)

群晖上部署了,插件也加入了ip和端口

**Comment by xjasonlyu** [comment]
你应该没挂代理，请求超时了吧。。

**Comment by gm-fire** [comment]
> 你应该没挂代理，请求超时了吧。。

有代理,路由器挂着.
另外日志文件经常看到这个

ERROR:root:"http://www.m45e.com/" returned an error. Could not collect tokens. | stdout
-- | --

**Comment by xjasonlyu** [comment]
m45e那個是javlibrary的，那個網址掛了，所以導致javlib不能用。

你能不能提供一下詳細的日誌。

**Comment by gm-fire** [comment]
[avdc-api.html.zip](https://github.com/xjasonlyu/jellyfin-plugin-avdc/files/6209291/avdc-api.html.zip)
群晖docker导出的日志

**Comment by xjasonlyu** [comment]
你连接都超时了，是你的网络问题。简直直接在容器环境变量里加代理。

**Comment by gm-fire** [comment]
使用 CloudFlare Worker 免费部署地址可以嘛?JavScraper配置里面那个

**Comment by xjasonlyu** [comment]
不可以，不是一个东西。要类似于：`HTTP_PROXY=http://192.168.1.2:8000`这样的。

**Comment by gm-fire** [comment]
那谢谢了,这个HTTP代理搞不来.......

**Comment by xjasonlyu** [comment]
就是在[环境变量](https://github.com/xjasonlyu/avdc-api/wiki/Synology-%E7%BE%A4%E6%99%96%E5%AE%89%E8%A3%85%EF%BC%88%E5%8D%81%E5%88%86%E6%8E%A8%E8%8D%90%EF%BC%89#%E5%8F%AF%E9%80%89%E7%8E%AF%E5%A2%83%E8%AE%BE%E7%BD%AE)这一部填上你翻墙用的http代理地址。。

**Comment by gm-fire** [comment]
我意思是没有这个 http代理, 我路由上用的是 v2ray

**Comment by xjasonlyu** [comment]
v2ray支持本地http代理的XD

**Comment by gm-fire** [comment]
还没研究懂,估计不少我这样的小白 [流泪]

**Comment by gm-fire** [comment]
请问是在v2ray客户端设置 ?

**Comment by gm-fire** [comment]
谢谢,我再研究下

**Comment by gm-fire** [comment]
> v2ray支持本地http代理的XD

刚拉的镜像刮削不了封面
[avdc-api.html.zip](https://github.com/xjasonlyu/jellyfin-plugin-avdc/files/6212824/avdc-api.html.zip)

**Comment by xjasonlyu** [comment]
avdc.db需要重新下載一下

**Comment by gm-fire** [comment]
ok,可以了,谢谢!

**Comment by lovelively** [comment]
请问您能指导一下这个http代理的问题吗，您是怎样解决的

**Comment by gm-fire** [comment]
> 请问您能指导一下这个http代理的问题吗，您是怎样解决的

Use the following configure as your "inbound" or put it in the "inboundDetour" list:

{
  "port": 3128,
  "listen": "0.0.0.0",
  "protocol": "http",
  "settings": {
    "timeout": 0
  }
}

如果你也是用v2ray可以参考下
