### ISSUE TITLE
v2022.0522.1120版本net core更新到6.0引起的问题

### ISSUE THREAD

**Issue by 9iks** [xjasonlyu/jellyfin-plugin-avdc#51]
在jellyfin 10.7中，net的版本是5.0，插件安装后，无法正常启动

**Comment by xjasonlyu** [comment]
是的，用10.7的暂时别更新插件了，建议倒退回去。

新版本插件只是做了平台兼容更新，没有加入任何新的功能，所以不需要更新。

**Comment by 9iks** [comment]
已经退回旧版，刮削的时候全部显示404，还不知道是插件的问题或是avdc-api的问题

**Comment by xjasonlyu** [comment]
你退回了哪个版本？avdc-api没有更新，所以不存在什么问题，旧版本插件之前能用那就是能用，也不应该有问题才对

**Comment by xjasonlyu** [comment]
那些不是插件的问题，-_是不同的番号

**Comment by 9iks** [comment]
早期用JavScraper的时候，目录的命名就比较随意，所以一直延续了下来，换了avdc后没有调整目录名，所以出现了这一状况

**Comment by cyril-cheng** [comment]
如何禁止插件更新？退回以后它又会自动更新到最新版本。。。。
