### ISSUE TITLE
扫描媒体库，元数据可以识别出，封面加载不出来，但是单个识别可以替换

### ISSUE THREAD

**Issue by lovelively** [xjasonlyu/jellyfin-plugin-avdc#9]
扫描媒体库，元数据可以识别出，封面加载不出来，但是单个识别可以替换，请问是什么问题呢，大神原谅我比较小白，不太会描述，请问日志怎样提取呢

**Comment by xjasonlyu** [comment]
Jellyfin: Dashboard-> logs
avdc-api: 找一下docker這個容器的日誌

**Comment by lovelively** [comment]
[xjasonlyu-avdc-api1.zip](https://github.com/xjasonlyu/jellyfin-plugin-avdc/files/6254960/xjasonlyu-avdc-api1.zip)
应该是这个吧，麻烦您了

**Comment by xjasonlyu** [comment]
1. 你網絡似乎不好，經常有超時
2. 你文件是不是沒有按規則命名
3. 你插件版本是多少。。

**Comment by lovelively** [comment]
1.容器里面那个环境变量HTTP代理我不明白怎么填，就没有填，但是我有科学环境，就是不知道怎么应用到这上面
2.文件名大部分为我从javdb复制的原本番号加标题，小部分为番号-C
3.插件版本为2021.0402.1032.0

**Comment by lovelively** [comment]
刚更新最新插件又刷了一下还是不行，是因为网络问题吗

**Comment by xjasonlyu** [comment]
1. 比如你的HTTP代理地址是192.168.1.2:8080，环境变量就填HTTP_PROXY=http://192.168.1.2:8080，有些时候容器里不一定会走全局的科学上网环境，看你配置的。。
2. 文件命名参考README的命名规则，不能带中文标题，可以有`-C`。
3. 插件再更新一下。

**Comment by lovelively** [comment]
1.大佬，这个代理地址我可以直接查询节点的ip地址填上去吗？
2.我的文件90%都是javdb复制的原始标题，按说这些正常应该能识别的吧
3.插件已更新了。
请问最主要原因是不是代理通道不通呀

**Comment by xjasonlyu** [comment]
1. 明显不能，，要http代理地址，你的客户端肯定提供的。
2. `XXX-123`这样的，你有的没有加`-`会导致识别不出来，你加了的中文标题也会影响番号的识别率。

似乎代理和命名都有关系

**Comment by lovelively** [comment]
1.代理的问题我再去学习一下吧
2.您的意思是我的文件识别不出来都是和文件名有关？而不是因为代理的原因是吗？

**Comment by xjasonlyu** [comment]
似乎都有，不过中文标题确实是可以忽略掉，晚点更新插件过滤一下。

**Comment by lovelively** [comment]
感谢您了，我还是再去学习一下吧，也期待您的更新

**Comment by LNai** [comment]
你好 你可以参考下这个 #11

**Comment by lovelively** [comment]
> 你好 你可以参考下这个 #11

非常感谢您，我去试一下
